### ISSUE TITLE
Onde posso aplicar?

### ISSUE THREAD

**Issue by luxu** [agencia-tecnologia-palmas/boilerplate-manager#1]
Criei um projeto do zero pra testar o projeto de vcs mas num entendi como eu "agrego" a esse projeto novo o projeto de vcs. 
Att,
Luciano

**Comment by claysllanxavier** [comment]
### Intalação

Para instalar o boilerplate-manager:

```shell
    $ pip install boilerplate-manager
```

Adicione `core` na seu `INSTALLED_APPS`:

```python
    INSTALLED_APPS = [
        # other apps
        "core",
    ]
```

Adicione o `core.urls` nas urls principais do seu projeto:

```python
    urlpatterns = [
        # other urls
        path('core/', include('core.urls'), name='core'),
    ]
```
Run 
```shell 
    $ python manage.py migrate
```
para migrar as tabelas par ao banco de dados

Run 
```shell 
    $ python manage.py runserver
```
para iniciar o servidor

Visite http://127.0.0.1:8000/core/ .  

### Uso
Crie uma nova app para seu projeto.

Para que seja gerado os arquivos para o seu model, crie uma app nova e escreva somente os models dela. O models devem extender de `Base`.

Exemplo:

 ```python
 #others imports
 from core.models import Base

#Create your models here.
class NameModel(Base):
    ...
 ```
Depois disso, execute  o comando para que seja gerados os arquivos da sua app.

 ```shell
    $ python manage.py build <your_app_name> 
 ```
Esse comando irá gerar todos os forms, views, Api Rest e os templates para sua app baseada em seu model.
Após esse procedimento adicione sua app na urls principais do seu projeto:

```python
    urlpatterns = [
        # other urls
        path('core/<your_app>', include('<your_app>.urls'), name='<your_app>'),
    ]
```
Execute
 
```shell 
    $ python manage.py migrate
```
para migrar as tabelas par ao banco de dados

Execute 
 
```shell 
    $ python manage.py runserver
```
para iniciar o servidor

Visite http://127.0.0.1:8000/core/ e você poderá ver sua o CRUD completo de todos os models da sua app, além de poder utilizar a API dela.

**Comment by luxu** [comment]
Num existe build no **manage.py**

```
(venv) PS C:\Users\luxu\Desktop\boiler> python manage.py build boiler
Unknown command: 'build'
Type 'manage.py help' for usage.

```

**Comment by claysllanxavier** [comment]
Mesmo após executar o comando 
```shell
pip install boilerplate-manager
```
e adicionando o `core` no seu `INSTALLED_APPS`:

```python
    INSTALLED_APPS = [
        # other apps
        "core",
    ]
```
?

**Comment by claysllanxavier** [comment]
Mas para funcionar o `build` você deve realizar o procedimento acima.

**Comment by luxu** [comment]
blz. vlw, pode fechar a issue.
